[package]
name = "chick_vs_rex"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.2"
rayon = "1.12.0"

[lints.rust]
unused = "allow"   

[lints.clippy]
new_without_default = "allow"   

[profile.release]
debug = true

[dev-dependencies]
rayon = "1.12.0"
criterion = { version = "=0.8.2", features = [
   "rayon", 

   # to get html display results and charts however, 
   # this might be active by default for this version
   # "html-reports",

   "plotters",
   "cargo_bench_support",
   "async_tokio"
] }

[[bench]]
name = "bench1"
harness = false
